### ISSUE TITLE
Stopping time

### ISSUE THREAD

**Issue by HazemKhaledAbdallah** [venturi123/DRLinFluids#18] opened 2024-05-01 00:28 UTC
Hello sir ,
Thanks for sharing the amazing work and your effort is appreciated .
I have a question , iam working on the square example and i followed your instructions by running multiprocessing training file.
Now i exceed 1500 epock  and solution doesnt stop . So should i stop it or when it have to stop i noticed that maximum episode is 1000 and at the same time reward threshold is 100. Also when i have to use another example using your work , what is the files that i have to consider for changing parameters and the files which shouldnt be modified.
Regards

**Comment by venturi123** [comment] 2024-05-02 01:51
Hi @HazemKhaledAbdallah ,

Thanks for your interest in our work. 

For your first question, yes, we intentionally set a large epoch number. You can refer to this [line](https://github.com/venturi123/DRLinFluids/blob/594090d3fa4189e39638c8490f9189b87a113086/examples/square2D_multiprocessing/DRLinFluids_square/launch_multiprocessing_traning_square.py#L37) to manually control when to stop the training process, depending on whether the learning curve has converged. Alternatively, you can adjust the number in this line to set a specific number of epochs.

Then second question, all adjustable parameters are configured through the `get_args()` function. You can directly modify the default values of the parameters within this function, or you can specify them via command line arguments when running the .py file. Here is a brilliant [guide](https://docs.python.org/3/howto/argparse.html) for the usage for your information.

Regards,
Qiulei

**Comment by HazemKhaledAbdallah** [comment] 2024-05-03 04:25
Hi
Thanks alot for your reply and guidance .
i didnt stop the solution and now it seems to be 2999 episode so  is this error because number of episodes already finished or there is a specific problem happened .
here is  the end of training  :Epoch #2999: 101it [01:48,  1.09s/it, alpha=0.000, env_step=301313, len=100, loss/actor=-19.891, loss/alpha=-0.005, loss/critic1=0.003, loss/critic2=0.006, n/epEpoch #2999: 101it [01:48,  1.07s/it, alpha=0.000, env_step=301313, len=100, loss/actor=-19.891, loss/alpha=-0.005, loss/critic1=0.003, loss/critic2=0.006, n/ep=0, n/st=20, rew=14.17]
Traceback (most recent call last):
  File "DRLinFluids_square/launch_multiprocessing_traning_square.py", line 366, in <module>
    test_sac_with_il()
  File "DRLinFluids_square/launch_multiprocessing_traning_square.py", line 356, in test_sac_with_il
    assert stop_fn(result['best_reward'])
KeyError: 'best_reward'
Regards

**Comment by venturi123** [comment] 2024-05-03 09:34
If I understand correctly, the correct usage of the command line should be as follows:
```
python launch_multiprocessing_training_square.py \
--epoch 400 \
--step-per-epoch 100
```
You can find all available parameters in the `get_args()` function within `launch_multiprocessing_training_square.py`.

Regarding the error you mentioned, it appears to trigger the `stop_fn` for reaching to the training epoch limitation you set. I believe you can safely ignore them as they are part of the intended behavior.

**Comment by HazemKhaledAbdallah** [comment] 2024-05-03 10:02
Ok thanks alot.
Yes i get your point.
But my second question was regarding using a different environment,  for example flow around any other body , should in this case care about the training file or i must change the other files inside DRLFluid like tianshoue.py.
I appreciate your help and patience.
Regards

**Comment by venturi123** [comment] 2024-05-03 11:20
If your goal is to adapt DRLinFluids for a custom CFD scenario, you can simply replace the `env*` folders, which are essentially standard OpenFOAM cases. Additionally, you should update the relevant parameters in `launch_multiprocessing_training_square.py`, such as `foam_params`, `agent_params`, `state_params`, etc., to suit your specific requirements.

We have prepared three example cases for different flow scenarios. I recommend reviewing them one by one, as this should provide a comprehensive understanding of the pipeline used in DRLinFluids.

**Comment by venturi123** [comment] 2024-05-10 01:40
Happy to know that. There seem to be no more questions so that I will close the issue now. : )

**Closed by venturi123** 2024-05-10 01:40 UTC

**Comment by HazemKhaledAbdallah** [comment] 2024-05-30 13:09
Hello sir 
Excuse me , i am trying to run my own case but iam facing a problem with the parallel process and receiving this error ( File "/home/hazemabdallah/DRLinFluids/examples/Hazem-DRL/DRLinFluids/cfd.py", line 134, in run_init
    subprocess.run(
  File "/opt/miniconda3/envs/DRLinFluids/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'cd /home/hazemabdallah/DRLinFluids/examples/Hazem-DRL/env01 && . /opt/openfoam8/etc/bashrc && decomposePar -force > /dev/null' returned non-zero exit status 134.
(DRLinFluids) Singularity> 
)
Also i find that when iam trying to run the case in parallel with out the training file , by using (mpirun -np 5 pimpleFoam -parallel). I face error and simulation didn't start and also this happened when i tried to run your case without the training file , i find that parallel mode is not working with me.
i did a lot of modifications but once i delete the functions and libraries from the control dic file , in this case parallel mode worked with me in simulation  but this will not help because i need these function in running the multi process training .
Sorry for your time and please let me know if there are any suggestions as i did a lot of tries and also tried to modify the code and run it using single training process and it doesn't work with me .
Best regards

**Comment by venturi123** [comment] 2024-05-31 03:38
Sounds weird. If you can't run the case in a pure OpenFOAM, I guess there is something wrong with your command flow. 

What happens if you run the commands within the singularity container one by one in the terminal?

```
cd /home/hazemabdallah/DRLinFluids/examples/Hazem-DRL/env01
. /opt/openfoam8/etc/bashrc
decomposePar -force
mpirun -np 5 pimpleFoam -parallel
```

**Comment by HazemKhaledAbdallah** [comment] 2024-05-31 05:05
Now your case worked with me as a pure openFoam , but for my case , it works well in series  , but this what happen when i try to run it at parallel :Build  : 8-1c9b5879390b
Exec   : pimpleFoam -parallel
Date   : May 31 2024
Time   : 15:02:10
Host   : "mu00234250"
PID    : 75541
I/O    : uncollated
Case   : /home/hazemabdallah/DRLinFluids/examples/Hazem-DRL/env02
nProcs : 5
Slaves : 
4
(
"mu00234250.75542"
"mu00234250.75543"
"mu00234250.75544"
"mu00234250.75545"
)

Pstream initialized with:
    floatTransfer      : 0
    nProcsSimpleSum    : 0
    commsType          : nonBlocking
    polling iterations : 0
sigFpe : Enabling floating point exception trapping (FOAM_SIGFPE).
fileModificationChecking : Monitoring run-time modified files using timeStampMaster (fileModificationSkew 10)
allowSystemOperations : Allowing user-supplied system call operations

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //
Create time

Create mesh for time = 1


PIMPLE: No convergence criteria found


PIMPLE: Operating solver in transient mode with 1 outer corrector
PIMPLE: Operating solver in PISO mode


Reading field p

[0] 
[0] 
[0] --> FOAM FATAL ERROR: 
[0] cannot find file "/home/hazemabdallah/DRLinFluids/examples/Hazem-DRL/env02/processor0/1/p"
[0] 
[0]     From function virtual Foam::autoPtr<Foam::ISstream> Foam::fileOperations::uncollatedFileOperation::readStream(Foam::regIOobject&, const Foam::fileName&, const Foam::word&, bool) const
[0]     in file global/fileOperations/uncollatedFileOperation/uncollatedFileOperation.C at line 538.
[0] 
FOAM parallel run exiting
[0] 
[1] 
[1] 
[1] --> FOAM FATAL ERROR: 
[1] cannot find file "/home/hazemabdallah/DRLinFluids/examples/Hazem-DRL/env02/processor1/1/p"

**Comment by HazemKhaledAbdallah** [comment] 2024-05-31 08:28
Thanks alot  ,it works with me in parallel finally , but i need to make sure from something because error happen with me  when i run the multiprocessing training .
My control dic the start time is 0 and end time is 60 with deltat 0.05 , write interval 1 and i changed that in foam parameter at training file , what about 'cfd_init_time': 0.005,  # 初始化流场，初始化state (i make it  0) and  wait_num=args.training_num, timeout=0.2 ( i make it 70).
is it right because my  simulation time is different or i shouldnt change them . 






(DRLinFluids) (DRLinFluids) Singularity> python DRLinFluids_square/launch_multiprocessing_traning_square.py
OpenFOAM_init running time： 2.62 s
OpenFOAM_init running time： 2.63 s
OpenFOAM_init running time： 2.67 s
OpenFOAM_init running time： 2.55 s
OpenFOAM_init running time： 2.67 s
OpenFOAM_init running time： 2.67 s
(224,) (1,)
/opt/miniconda3/envs/DRLinFluids/lib/python3.8/site-packages/tianshou/data/collector.py:369: UserWarning: Using async setting may collect extra transitions into buffer.
  warnings.warn("Using async setting may collect extra transitions into buffer.")
True False
Epoch #1:   0%|                                         | 0/100 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "DRLinFluids_square/launch_multiprocessing_traning_square.py", line 366, in <module>
    test_sac_with_il()
  File "DRLinFluids_square/launch_multiprocessing_traning_square.py", line 340, in test_sac_with_il
    result = offpolicy_trainer(
  File "/opt/miniconda3/envs/DRLinFluids/lib/python3.8/site-packages/tianshou/trainer/offpolicy.py", line 129, in offpolicy_trainer
    return OffpolicyTrainer(*args, **kwargs).run()
  File "/opt/miniconda3/envs/DRLinFluids/lib/python3.8/site-packages/tianshou/trainer/base.py", line 418, in run
    deque(self, maxlen=0)  # feed the entire iterator into a zero-length deque
  File "/opt/miniconda3/envs/DRLinFluids/lib/python3.8/site-packages/tianshou/trainer/base.py", line 270, in __next__
    data, result, self.stop_fn_flag = self.train_step()
  File "/opt/miniconda3/envs/DRLinFluids/lib/python3.8/site-packages/tianshou/trainer/base.py", line 361, in train_step
    result = self.train_collector.collect(
  File "/opt/miniconda3/envs/DRLinFluids/lib/python3.8/site-packages/tianshou/data/collector.py", line 462, in collect
    result = self.policy(self.data, last_state)
  File "/opt/miniconda3/envs/DRLinFluids/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/miniconda3/envs/DRLinFluids/lib/python3.8/site-packages/tianshou/policy/modelfree/sac.py", line 115, in forward
    dist = Independent(Normal(*logits), 1)
  File "/opt/miniconda3/envs/DRLinFluids/lib/python3.8/site-packages/torch/distributions/normal.py", line 56, in __init__
    super().__init__(batch_shape, validate_args=validate_args)
  File "/opt/miniconda3/envs/DRLinFluids/lib/python3.8/site-packages/torch/distributions/distribution.py", line 62, in __init__
    raise ValueError(
ValueError: Expected parameter loc (Tensor of shape (5, 1)) of distribution Normal(loc: torch.Size([5, 1]), scale: torch.Size([5, 1])) to satisfy the constraint Real(), but found invalid values:
tensor([[nan],
        [nan],
        [nan],
        [nan],
        [nan]])

After that i find initial time is 0 and final is 1.
So is there something wrong with my setting or something else i should change .
Best regards

**Comment by HazemKhaledAbdallah** [comment] 2024-06-05 02:04
Excuse me , i did a lot of changes a gain to my case to be exactly similar to yours but still face sililar problems like cant multiply M1 and M2 with different dimensions and some times error due to different shape , and at the end this error :  File "/opt/miniconda3/envs/DRLinFluids/lib/python3.8/site-packages/tensorforce/execution/runner.py", line 171, in __init__
    self.agent = Agent.create(
  File "/opt/miniconda3/envs/DRLinFluids/lib/python3.8/site-packages/tensorforce/agents/agent.py", line 64, in create
    assert agent.spec[key] >= value
So , could you tell me , what is the most important parameter that i have to check in my new case or in my post processor outputs which will help in running the code .
Best regards

**Comment by venturi123** [comment] 2024-06-05 14:59
Hi @HazemKhaledAbdallah ,

For your first question, If I understand correctly, you must perform a CFD simulation before running the DRL training to obtain an initial state. But note that this is solely for obtaining the initial state and is unrelated to the following training process. 

Secondly, from the error raised, the shape error often occurs on the incorrect definition of `entry_dict` in [these lines](https://github.com/venturi123/DRLinFluids/blob/de66d9dcb027ee4556744b11bc57adfb683dd028/examples/cylinder2D_multiprocessing/DRLinFluids_cylinder/launch_multiprocessing_traning_cylinder.py#L31-L62). You can set an entire `entry_dict` like this:

```
entry_dict = {
    'U': {
        'JET1': {
            'q0': '{x}',
        },
        'JET2': {
            'q0': '{-x}',
        }
    }
}
```

If you look back at the OpenFOAM file, you will find boundary condition dictionary variables with the same names. If you need to set your boundary conditions, write them in a nested format similar to this variable, which is actually in JSON format. Generally speaking, it's hard to say the exact type of error based on the information you provided. You may first check the content I mentioned above.

**Comment by HazemKhaledAbdallah** [comment] 2024-06-06 02:16
Hi , thanks for reply .
Yes i solved the case then i copied U and P files from last folder and put them in 0 folder .
Also i copied the jet boundary  like that:
boundaryField
{
    out
    {
        type            zeroGradient;
    }
    in
    {
        type            fixedValue;
        value           uniform (1 0 0);
    }
    sym1
    {
        type            symmetry;
    }
    sym2
    {
        type            symmetry;
    }
    cylinder
    {
        type            fixedValue;
        value           uniform (0 0 0);
    }
    JET1
    {
        type            incrementalJetParabolicVelocity;
        omega           0.17453293;
        r               0.05;
        theta0          1.5707963;
        q0              0;
        q1              0;
        alpha           0.1;
        t0              0;
        deltaT          0.05;
        value           uniform (-0 0 0);
    }
    JET2
    {
        type            incrementalJetParabolicVelocity;
        omega           0.17453293;
        r               0.05;
        theta0          1.5707963;
        q0              0;
        q1              0;
        alpha           0.1;
        t0              0;
        deltaT          0.05;
        value           uniform (0 -0 0);
    }
    frontAndBackPlanes
    {
        type            empty;
    }
}
And this is the details of error which i relieve:
 (DRLinFluids) Singularity> python DRLinFluids_cylinder/launch_multiprocessing_traning_cylinder.py
OpenFOAM_init running time： 2.64 s
OpenFOAM_init running time： 2.86 s
OpenFOAM_init running time： 2.74 s
OpenFOAM_init running time： 2.75 s
OpenFOAM_init running time： 2.77 s
WARNING:root:No min_value bound specified for state.
Agent defined DONE!
Runner defined DONE!
Episodes:   0%| | 0/3000 [00:00, reward=0.00, ts/ep=0, sec/ep=0.00, ms/ts=0.0, aTraceback (most recent call last):
  File "DRLinFluids_cylinder/launch_multiprocessing_traning_cylinder.py", line 163, in <module>
    runner.run(num_episodes=shell_args['num_episodes'],
  File "/opt/miniconda3/envs/DRLinFluids/lib/python3.8/site-packages/tensorforce/execution/runner.py", line 543, in run
    self.handle_act(parallel=n)
  File "/opt/miniconda3/envs/DRLinFluids/lib/python3.8/site-packages/tensorforce/execution/runner.py", line 577, in handle_act
    actions = self.agent.act(states=self.states[parallel], parallel=parallel)
  File "/opt/miniconda3/envs/DRLinFluids/lib/python3.8/site-packages/tensorforce/agents/agent.py", line 386, in act
    return super().act(
  File "/opt/miniconda3/envs/DRLinFluids/lib/python3.8/site-packages/tensorforce/agents/recorder.py", line 225, in act
    states, batched, num_parallel, is_iter_of_dicts, input_type = self._process_states_input(
  File "/opt/miniconda3/envs/DRLinFluids/lib/python3.8/site-packages/tensorforce/agents/recorder.py", line 549, in _process_states_input
    assert states.shape[1:] == self.states_spec.value().shape
AssertionError
(DRLinFluids) Singularity> 
thanks for your time 
Regards

**Comment by HazemKhaledAbdallah** [comment] 2024-06-12 02:31
Hello sir 
Excuse me , i replaced my mesh with your mesh and the code worked .when iam trying to see the different between the output of the 2 meshes , i find that in your mesh the internal field (1.2820425 0.17385801 0)
(1.2178368 0.31982903 0)
(1.2732198 0.30549374 0)   , and the probe output  (1.7188175 0.062868932 0) (1.8101375 0.32067824 0) (1.2214535 -0.57574611 0)   seems to have a value totally zero in Z. In the other hand , i find the output from my mesh is like that for internal field (1.138613 0.019095374 1.2146722e-22)
(1.134348 0.01929165 -5.6189388e-22)
(1.1297245 0.019827834 2.128516e-21) and the probe output is (1.0130351 0.18606949 -1.6441697e-20) (1.1878886 0.14980487 1.2302276e-21) (1.1568558 0.22475693 -6.6358446e-21).
so do you think this is may be the reason for the AssertionError accordind to this part of the code : 
 # Store the initialized flow field result (state) in the _init file to avoid repeated reading and writing
			self.velocity_table_init = utils.read_foam_file(
				foam_root_path + f'/postProcessing/probes/0/U',
				dimension=self.foam_params['num_dimension']
			)
			self.pressure_table_init = utils.read_foam_file(
				foam_root_path + f'/postProcessing/probes/0/p',
				dimension=self.foam_params['num_dimension']
			)

		# state_space
		# using pressure as a training parameter
		if self.state_params['type'] == 'pressure':
			# 范围不限制
			self.state_space = spaces.Box(low=-np.Inf, high=np.Inf,
			                              shape=(int(self.state_params['probe_info'].shape[0]),), dtype=np.float32)
		# using velocity as a training parameter
		elif self.state_params['type'] == 'velocity':
			if self.foam_params['num_dimension'] == 2:
				self.state_space = spaces.Box(low=-np.Inf, high=np.Inf,
				                              shape=(2 * int(self.state_params['probe_info'].shape[0]),),
				                              dtype=np.float32)
			elif self.foam_params['num_dimension'] == 3:
				self.state_space = spaces.Box(low=-np.Inf, high=np.Inf,
				                              shape=(3 * int(self.state_params['probe_info'].shape[0]),),
				                              dtype=np.float32)
			else:
				assert 0, 'Simulation type error'
		else:
			assert 0, 'No define state type error'
thanks 
Best regards

**Comment by venturi123** [comment] 2024-06-12 15:40
It seems like the issue is with the initialization of the OpenFOAM environment. How do you usually initialize your case? Are you using DRLinFluids for this? I don't see obvious issues from your description. 

An alternative is that you could try initializing it manually. For instance, run the simulation w/o DRLinFluids for a few time steps, place it in the environment folder, then run the code directly, and see if everything gets back on track.

**Comment by HazemKhaledAbdallah** [comment] 2024-06-13 08:22
i did as you mentioned with the following parameter : startTime       0; endTime        0.025; deltaT           0.001; writeInterval   0.00125; . to achieve a slow motion for the case like yours .
then i make the following modifications in your foam parameters :
    'delta_t': 0.001,
    'solver': 'pimpleFoam',
    'num_processor': 2,
    'of_env_init': '. /opt/openfoam8/etc/bashrc',
    'cfd_init_time': 0.025,
    'num_dimension': 2,
    'verbose': False    'interaction_period': 0.00125,
    'writeInterval': 0.00125,
    'deltaT': 0.001,
and again changed my start time to be 0.025 instead of 0 and i didnt delete  the post processing folders tell this time 0.025.
and also recieved same error 
assert states.shape[1:] == self.states_spec.value().shape
AssertionError

**Comment by HazemKhaledAbdallah** [comment] 2024-06-27 06:28
Hello sir , it works with me finally and i guess the problem may relate to CFD initial time , vortex shedding time , writing interval and how much time should it take for initialization.
Because those are the parameters which i keep changing tell code start working , i hope it will give me a good results after finish training and if you have any suggestions about parameters that i have to tune or consider to help me achieve good results during training process, please let me know.
Thanks for your support .
Regards
